---
- name: yum-cron install
  package:
    name: yum-cron
    state: present
  notify:
    - enable yum-cron
    - restart yum-cron

- name: yum-utils install
  package:
    name: yum-utils
    state: present

# yum cron -----------------------------------------------------------------------------------------
- name: /etc/yum/yum-cron.conf
  template:
    src: "yum-cron.conf.j2"
    dest: /etc/yum/yum-cron.conf
    owner: root
    group: root
    mode: 0644

- name: /etc/cron.hourly/0yum-hourly.cron
  template:
    src: "0yum-hourly.cron.j2"
    dest: /etc/cron.hourly/0yum-hourly.cron
    owner: root
    group: root
    mode: 0755

- name: restart yum-cron
  service:
    name: yum-cron
    state: restarted
    enabled: yes
