---
- name: apt install auto package upgrades
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  vars:
    packages:
      - debconf-utils
      - unattended-upgrades
      - apt-listchanges

#  $ echo 'unattended-upgrades unattended-upgrades/enable_auto_updates boolean true' \
#  | sudo debconf-set-selections
#  $ sudo dpkg-reconfigure -f noninteractive -plow unattended-upgrades
- name: create APT auto-upgrades configuration
  template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: create unattended-upgrades configuration
  template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
